spring.application.name=student_management
spring.data.jdbc.dialect=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.banner.location=classpath:banner.txt
spring.datasource.username=user
spring.datasource.password=password
student.default-username=admin@rupp.com
student.default-password=password123
spring.datasource.url=jdbc:postgresql://152.42.210.163:5432/student
student.jwt-secret=7BC36EA32F34646C6AD968014C4608E73E9F4CA230F34ACE72CD3E39B6A0BD639CFFBC7E999F97174965199B2E5642707D813F4E576125580E4E39613B2848E2